### ISSUE TITLE
[Bug report] saving an image into gallery loses quality

### ISSUE THREAD

**Issue by joaquingrech** [fluttercandies/saver_gallery#15]
### Version

latest

### Platforms

iOS

### Device Model

iphone 14

### flutter info

```sh
all good
```

### How to reproduce?

I download a picture from the internet and save it to the gallery. For some reason, using the package the quality lost is huge. I even tried with 98% at quality, which should give a perfect representation and it looks like it is set at 40%... horrible results. I tested on Android and it seems ok, this seems to be a problem only with iOS. The file I download is a .webp image.

### Logs

```sh
no need
```

### Example code (optional)

```Dart
// Fetching the image from the internet
      var response = await http.get(Uri.parse(imageUrl));
      if (response.statusCode == 200) {
         // Saving the image to the gallery
        SaveResult result = await SaverGallery.saveImage(
            Uint8List.fromList(response.bodyBytes),
            quality: 98,
            name: 'temp.webp',
            androidExistNotSave: true);
```

**Comment by zhangruiyu** [comment]
saveImageToGallery will convert to jpg, which is exactly what happens, so you can use saveFileToGallery
