### ISSUE TITLE
[Bug report] iOS market submission error

### ISSUE THREAD

**Issue by raccoondev85** [fluttercandies/saver_gallery#16]
### Version

3.0.5

### Platforms

iOS

### Device Model

iphone

### flutter info

```sh
good
```

### How to reproduce?

I got email feedback from iOS submission.

ITMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/saver_gallery.framework/saver_gallery.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

Any idea?

### Logs

```sh
none
```

**Comment by SmartfySolutions** [comment]
I have same issuese

**Comment by sabaudani** [comment]
I am also facing the same issue.

**Comment by SkyOfFeather** [comment]
I have same issuese

**Comment by Yousef-Alabdulhadi** [comment]
Same here

**Comment by zhangruiyu** [comment]
I have seen this problem, but I do not know how to solve it. If someone solves it, please submit it to pr. I will also find a way in the next period

**Comment by zhangruiyu** [comment]
![image](https://github.com/user-attachments/assets/cf0be28c-f061-4339-a50a-5eab50aaee60)
And I tried to submit. And it worked. I can't test it so far

**Comment by zhangruiyu** [comment]
I have pushed version 3.0.6, I can try to update it, but I am not sure whether it is repaired, please help verify it

**Comment by RazvanTamazlicariu** [comment]
> ![image](https://private-user-images.githubusercontent.com/10591822/362321333-cf0be28c-f061-4339-a50a-5eab50aaee60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjQwMDcsIm5iZiI6MTcyNDg2MzcwNywicGF0aCI6Ii8xMDU5MTgyMi8zNjIzMjEzMzMtY2YwYmUyOGMtZjA2MS00MzM5LWE1MGEtNWVhYjUwYWFlZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE2NDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNWU3MGU5ZDM0MTc5ODU3NWY5NzNmNmY0Y2EyMzFlNTQ4YmQyM2MzZTdhNDAwM2Y1OGQ2NzVhNWZiYzA2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZwUTcEqjy8Wb2CI7awr54lqf4RDlIQCasdahd-l5tTg) And I tried to submit. And it worked. I can't test it so far

it works when you push it on TestFlight, but when you submit the build for review, it gives you the error.

**Comment by zhangruiyu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/10591822/362321333-cf0be28c-f061-4339-a50a-5eab50aaee60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjQwMDcsIm5iZiI6MTcyNDg2MzcwNywicGF0aCI6Ii8xMDU5MTgyMi8zNjIzMjEzMzMtY2YwYmUyOGMtZjA2MS00MzM5LWE1MGEtNWVhYjUwYWFlZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE2NDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNWU3MGU5ZDM0MTc5ODU3NWY5NzNmNmY0Y2EyMzFlNTQ4YmQyM2MzZTdhNDAwM2Y1OGQ2NzVhNWZiYzA2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZwUTcEqjy8Wb2CI7awr54lqf4RDlIQCasdahd-l5tTg) And I tried to submit. And it worked. I can't test it so far
> 
> it works when you push it on TestFlight, but when you submit the build for review, it gives you the error.

Was it rejected by Apple's reviewers?

**Comment by zhangruiyu** [comment]
I tested 3.0.6 and found that it no longer appears, and if there is no follow-up feedback, I will close the issue

**Comment by RazvanTamazlicariu** [comment]
I cloned the repo and made 2 changes,that seems to fix the issue for me:
1. remove empty line from PrivacyInfo.xcprivacy
2. added : `  s.resources = 'Resources/PrivacyInfo.xcprivacy'` in saver_gallery.podspec
