### ISSUE TITLE
引入插件后打包失败

### ISSUE THREAD

**Issue by mdddj** [fluttercandies/saver_gallery#4]
打包报错: 
<img width="1742" alt="image" src="https://user-images.githubusercontent.com/29020213/225508567-424c45ae-1258-4ecd-bb93-059a39dd5c2e.png">

解决方案
将这个注释就可以打包了
<img width="791" alt="image" src="https://user-images.githubusercontent.com/29020213/225508702-c25e0014-34f3-48f8-97a6-8036d7147357.png">

**Comment by zhangruiyu** [comment]
更新到2.1吧 我给kt降级了

**Comment by zhangruiyu** [comment]
2.0.1版本
